<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dengsh" name="Test" tests="3" failures="3" timestamp="30 Aug 2015 13:52:47 GMT" time="3.016" errors="0">
  <testcase name="run" time="2.09" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第2行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第2行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:97)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.392" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第1行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第1行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:97)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.167" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第3行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第3行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:97)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- Test -->
