<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dengsh" name="ApiTest" tests="3" failures="3" timestamp="30 Aug 2015 14:11:36 GMT" time="15.636" errors="0">
  <testcase name="run" time="2.276" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第3行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第3行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.095" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第1行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第1行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
  <testcase name="run" time="0.091" classname="com.kaikeba.server.api.utils.HTTPRequestTest">
    <failure type="java.lang.AssertionError" message="第2行数据，接口测试失败！">
      <![CDATA[java.lang.AssertionError: 第2行数据，接口测试失败！
	at com.kaikeba.server.api.utils.HTTPRequestTest.run(HTTPRequestTest.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- run -->
</testsuite> <!-- ApiTest -->
